---
- :name: Jugo De La Granja De Naranja - 3400ml
  :price: 26.0
  :stock: 245
- :name: Queso Crema Philadelphia Barra - 180gr
  :price: 25.5
  :stock: 21
- :name: Manzana Fuji Importada Libra
  :price: 10.0
  :stock: 54
- :name: Ensalada Express Kale Clamshell - 5 Onzas
  :price: 19.85
  :stock: 9
- :name: Filete De Tilapia Congelado - 1Lb
  :price: 12
  :stock: 85
- :name: 3 Pack Jabón de Tocador Antibacterial Protex Fresh 110 g
  :price: 19.75
  :stock: 110
- :name: Crema Nivea Corp Piel Extra Seca 1000Ml
  :price: 86.0
  :stock: 71
- :name: Samsung Celular M52 6Gb 128Gb
  :price: 599.0
  :stock: 39
- :name: Doradita Draft Botella 250Ml
  :price: 5.0
  :stock: 166
- :name: Heineken Cerveza Botella - 355ml
  :price: 9.0
  :stock: 105
- :name: Pan Bimbo Sandwich Blaco Xg - 720gr
  :price: 22.9
  :stock: 65
- :name: Pan Brohders Sandwich Integral con Semilla - 770gr
  :price: 21.55
  :stock: 48
- :name: Frijol Ducal Volteado Negro Doy Pack - 400gr
  :price: 8.9
  :stock: 45
- :name: Coctel Kerns Vegetales Almejas - 1000ml
  :price: 10.35
  :stock: 256
- :name: Te Lipton Limon 500Ml Pet
  :price: 5.5
  :stock: 384
- :name:  Aceite Ideal Mas Idealito - 2000ml
  :price: 23.65
  :stock: 189
- :name: Camaraon Freskamar Cocinado 454 Gr
  :price: 36
  :stock: 99
- :name: Led Samsung Smart 4K
  :price: 6,495.00
  :stock: 34
- :name: Sistema De Audio Aiwa 300W Pmpo
  :price: 595.00
  :stock: 13
- :name: Microfono Durabrand P/ Karaoke Bluethoot
  :price: 465
  :stock: 21